import type { Product, Collection, Review } from '@/lib/types';

export const collections: Collection[] = [
  { $id: '1', title: 'Pants', handle: 'Pants', imageId: 'category-pants', $collectionId: 'collections', $databaseId: 'rage-ecommerce', $createdAt: '', $updatedAt: '', $permissions: [], $sequence: 1 },
  { $id: '2', title: 'Vests', handle: 'Vests', imageId: 'category-vests', $collectionId: 'collections', $databaseId: 'rage-ecommerce', $createdAt: '', $updatedAt: '', $permissions: [], $sequence: 2 },
  { $id: '3', title: 'T-Shirts', handle: 'Tshirts', imageId: 'category-tshirts', $collectionId: 'collections', $databaseId: 'rage-ecommerce', $createdAt: '', $updatedAt: '', $permissions: [], $sequence: 3 },
  { $id: '5', title: 'Baby Tees', handle: 'Baby-tees', imageId: 'category-baby-tees', $collectionId: 'collections', $databaseId: 'rage-ecommerce', $createdAt: '', $updatedAt: '', $permissions: [], $sequence: 5 },
  { $id: '6', title: 'Shorts', handle: 'Shorts', imageId: 'category-shorts', $collectionId: 'collections', $databaseId: 'rage-ecommerce', $createdAt: '', $updatedAt: '', $permissions: [], $sequence: 6 },
  { $id: '7', title: 'Long Sleeves', handle: 'Long-Sleeves', imageId: 'category-long-sleeves', $collectionId: 'collections', $databaseId: 'rage-ecommerce', $createdAt: '', $updatedAt: '', $permissions: [], $sequence: 7 },
];

export const products: Product[] = [];

export const reviews: Review[] = [
  {
    $id: '1',
    name: 'Alex T.',
    rating: 5,
    review: 'The quality is insane. The fabric on these pants is tough but comfortable. Worth every penny!',
    productName: 'Gravity Cargo Pants',
    productId: 'product-1',
    $collectionId: 'reviews',
    $databaseId: 'rage-ecommerce',
    $createdAt: '',
    $updatedAt: '',
    $permissions: [],
    $sequence: 1,
  },
  {
    $id: '2',
    name: 'Jenna M.',
    rating: 5,
    review: 'Finally, a baby tee that actually fits well and feels great. So soft!',
    productName: 'Cropped Baby Tee',
    productId: 'product-2',
    $collectionId: 'reviews',
    $databaseId: 'rage-ecommerce',
    $createdAt: '',
    $updatedAt: '',
    $permissions: [],
    $sequence: 2,
  },
  {
    $id: '3',
    name: 'Carlos R.',
    rating: 4,
    review: 'This vest is my new go-to. It has so many useful pockets. Perfect for layering.',
    productName: 'Utility Vest',
    productId: 'product-3',
    $collectionId: 'reviews',
    $databaseId: 'rage-ecommerce',
    $createdAt: '',
    $updatedAt: '',
    $permissions: [],
    $sequence: 3,
  },
  {
    $id: '4',
    name: 'Aisha K.',
    rating: 5,
    review: 'Obsessed with this bandana! The pattern is so cool and the fabric is really high quality. Got so many compliments!',
    productName: 'Patterned Bandana',
    productId: 'product-4',
    $collectionId: 'reviews',
    $databaseId: 'rage-ecommerce',
    $createdAt: '',
    $updatedAt: '',
    $permissions: [],
    $sequence: 4,
  },
  {
    $id: '5',
    name: 'Mike P.',
    rating: 5,
    review: 'This is not just a t-shirt, it is a statement. The material is thick and the fit is perfect. Great for city life.',
    productName: 'Asymmetric Tee',
    productId: 'product-5',
    $collectionId: 'reviews',
    $databaseId: 'rage-ecommerce',
    $createdAt: '',
    $updatedAt: '',
    $permissions: [],
    $sequence: 5,
  },
];
