import type { Product, Collection, Review } from '@/lib/types';

export const collections: Collection[] = [
  { id: '1', title: 'Pants', handle: 'Pants', imageId: 'category-pants' },
  { id: '2', title: 'Vests', handle: 'Vests', imageId: 'category-vests' },
  { id: '3', title: 'T-Shirts', handle: 'Tshirts', imageId: 'category-tshirts' },
  { id: '4', title: 'Tanks', handle: 'Tanks', imageId: 'category-tanks' },
  { id: '5', title: 'Baby Tees', handle: 'Baby-tees', imageId: 'category-baby-tees' },
  { id: '6', title: 'Shorts', handle: 'Shorts', imageId: 'category-shorts' },
  { id: '7', title: 'Bandanas', handle: 'Bandanas', imageId: 'category-bandanas' },
];

export const products: Product[] = [
  // Pants
  {
    id: 'p1',
    name: 'Gravity Cargo Pants',
    slug: 'gravity-cargo-pants',
    category: 'Bottoms',
    subCategory: 'Pants',
    price: 149.99,
    rating: 4.6,
    reviewCount: 98,
    imageIds: ['men-pants-1'],
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Olive'],
    description: 'Ergonomic cargo pants with a tapered fit. Features 8 pockets for maximum utility and a stretch-fabric for comfort.',
    details: ['97% Cotton, 3% Elastane', 'Articulated Knees', 'D-Ring for keys', 'Adjustable Cuffs'],
    isTrending: true,
  },
  {
    id: 'p2',
    name: 'Tech-Fleece Joggers',
    slug: 'tech-fleece-joggers',
    category: 'Bottoms',
    subCategory: 'Pants',
    price: 129.99,
    rating: 4.8,
    reviewCount: 150,
    imageIds: ['men-pants-1'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Heather Grey'],
    description: 'Lightweight joggers for all-day comfort and style.',
    details: ['Fleece', 'Tapered fit', 'Side pockets'],
  },
  // Vests
  {
    id: 'v1',
    name: 'Utility Vest',
    slug: 'utility-vest',
    category: 'Tops',
    subCategory: 'Vests',
    price: 99.99,
    rating: 4.5,
    reviewCount: 60,
    imageIds: ['men-hoodie-1'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Khaki'],
    description: 'A functional vest with multiple pockets, perfect for layering.',
    details: ['Cotton-Nylon Blend', 'Multiple front pockets', 'Zipper closure'],
    isTrending: true,
  },
  // T-Shirts
  {
    id: 't1',
    name: 'Asymmetric Tee',
    slug: 'asymmetric-tee',
    category: 'Tops',
    subCategory: 'Tshirts',
    price: 69.99,
    rating: 4.9,
    reviewCount: 250,
    imageIds: ['men-shirt-1'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Gray'],
    description: 'A simple tee with a twist. The asymmetrical hem adds a modern edge to a classic staple.',
    details: ['100% Pima Cotton', 'Elongated Fit', 'Crew Neck', 'Sustainably Sourced'],
    isTrending: true,
  },
  // Baby Tees
  {
    id: 'bt1',
    name: 'Cropped Baby Tee',
    slug: 'cropped-baby-tee',
    category: 'Tops',
    subCategory: 'Baby-tees',
    price: 49.99,
    rating: 4.8,
    reviewCount: 200,
    imageIds: ['women-top-1'],
    sizes: ['XS', 'S', 'M'],
    colors: ['White', 'Pastel Pink', 'Black'],
    description: 'A cute and trendy cropped baby tee, perfect for a vintage look.',
    details: ['95% Cotton, 5% Spandex', 'Tight fit', 'Slightly cropped length'],
    isTrending: true,
  },
   // Tanks
  {
    id: 'ta1',
    name: 'Racerback Tank',
    slug: 'racerback-tank',
    category: 'Tops',
    subCategory: 'Tanks',
    price: 59.99,
    rating: 4.7,
    reviewCount: 130,
    imageIds: ['women-top-1'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'White', 'Teal'],
    description: 'A versatile racerback tank with a flattering fit.',
    details: ['90% Modal, 10% Spandex', 'Breathable fabric', 'Racerback design'],
  },
  // Shorts
  {
    id: 's1',
    name: 'Cargo Shorts',
    slug: 'cargo-shorts',
    category: 'Bottoms',
    subCategory: 'Shorts',
    price: 79.99,
    rating: 4.5,
    reviewCount: 90,
    imageIds: ['men-pants-1'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Khaki', 'Olive', 'Black'],
    description: 'Durable and stylish cargo shorts for any adventure.',
    details: ['100% Cotton Twill', 'Multiple pockets', 'Relaxed fit'],
  },
   // Bandanas
  {
    id: 'b1',
    name: 'Patterned Bandana',
    slug: 'patterned-bandana',
    category: 'Accessories',
    subCategory: 'Bandanas',
    price: 29.99,
    rating: 4.9,
    reviewCount: 300,
    imageIds: ['accessory-hat-1'],
    sizes: ['One Size'],
    colors: ['Paisley Black', 'Red', 'Blue'],
    description: 'A versatile bandana with a classic paisley print.',
    details: ['100% Cotton', '22x22 inches', 'Soft and durable'],
    isTrending: true,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    name: 'Alex T.',
    rating: 5,
    review: 'The quality is insane. The fabric on these pants is tough but comfortable. Worth every penny!',
    productName: 'Gravity Cargo Pants',
  },
  {
    id: '2',
    name: 'Jenna M.',
    rating: 5,
    review: 'Finally, a baby tee that actually fits well and feels great. So soft!',
    productName: 'Cropped Baby Tee',
  },
  {
    id: '3',
    name: 'Carlos R.',
    rating: 4,
    review: 'This vest is my new go-to. It has so many useful pockets. Perfect for layering.',
    productName: 'Utility Vest',
  },
  {
    id: '4',
    name: 'Aisha K.',
    rating: 5,
    review: 'Obsessed with this bandana! The pattern is so cool and the fabric is really high quality. Got so many compliments!',
    productName: 'Patterned Bandana',
  },
  {
    id: '5',
    name: 'Mike P.',
    rating: 5,
    review: 'This is not just a t-shirt, it is a statement. The material is thick and the fit is perfect. Great for city life.',
    productName: 'Asymmetric Tee',
  },
];
