import type { Product, Collection } from '@/lib/types';

export const collections: Collection[] = [
  { id: '1', title: "Men's Wear", handle: 'men', imageId: 'collection-men' },
  { id: '2', title: "Women's Wear", handle: 'women', imageId: 'collection-women' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Cybernetic Trench Coat',
    slug: 'cybernetic-trench-coat',
    category: 'Men',
    price: 299.99,
    originalPrice: 350,
    rating: 4.8,
    reviewCount: 124,
    imageIds: ['men-jacket-1', 'men-jacket-2'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Charcoal'],
    description: 'A trench coat reimagined for the urban explorer. Waterproof, breathable, and packed with hidden pockets.',
    details: ['100% Recycled Polyester', 'Waterproof Zipper', 'Magnetic Closures', 'Made in Future'],
    isTrending: true,
  },
  {
    id: '2',
    name: 'Gravity Cargo Pants',
    slug: 'gravity-cargo-pants',
    category: 'Men',
    price: 149.99,
    rating: 4.6,
    reviewCount: 98,
    imageIds: ['men-pants-1'],
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Olive'],
    description: 'Ergonomic cargo pants with a tapered fit. Features 8 pockets for maximum utility and a stretch-fabric for comfort.',
    details: ['97% Cotton, 3% Elastane', 'Articulated Knees', 'D-Ring for keys', 'Adjustable Cuffs'],
    isTrending: true,
  },
  {
    id: '3',
    name: 'Asymmetric Tee',
    slug: 'asymmetric-tee',
    category: 'Men',
    price: 69.99,
    rating: 4.9,
    reviewCount: 250,
    imageIds: ['men-shirt-1'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Gray'],
    description: 'A simple tee with a twist. The asymmetrical hem adds a modern edge to a classic staple.',
    details: ['100% Pima Cotton', 'Elongated Fit', 'Crew Neck', 'Sustainably Sourced'],
    isTrending: true,
  },
  {
    id: '4',
    name: 'Stealth Hoodie',
    slug: 'stealth-hoodie',
    category: 'Men',
    price: 189.99,
    rating: 4.7,
    reviewCount: 150,
    imageIds: ['men-hoodie-1'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Charcoal', 'Black'],
    description: 'A heavyweight hoodie with a high-neck design and concealed face covering for ultimate anonymity.',
    details: ['Heavyweight French Terry', 'Thumbhole Cuffs', 'Concealed Pockets', 'Oversized Hood'],
  },
  {
    id: '5',
    name: 'Architect Dress',
    slug: 'architect-dress',
    category: 'Women',
    price: 349.99,
    rating: 4.9,
    reviewCount: 88,
    imageIds: ['women-dress-1', 'women-dress-2'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black'],
    description: 'A statement dress with structured shoulders and a fluid, minimalist silhouette. Designed to command attention.',
    details: ['Japanese Crepe Fabric', 'Hidden Back Zipper', 'Fully Lined', 'Midi Length'],
    isTrending: true,
  },
  {
    id: '6',
    name: 'Origami Blouse',
    slug: 'origami-blouse',
    category: 'Women',
    price: 129.99,
    rating: 4.7,
    reviewCount: 75,
    imageIds: ['women-top-1'],
    sizes: ['XS', 'S', 'M'],
    colors: ['White', 'Black'],
    description: 'Inspired by the art of paper folding, this blouse features intricate pleats and a sharp collar.',
    details: ['100% Crisp Cotton Poplin', 'Concealed Button Placket', 'Sharp Point Collar', 'Made in Portugal'],
  },
  {
    id: '7',
    name: 'Liquid Metal Skirt',
    slug: 'liquid-metal-skirt',
    category: 'Women',
    price: 199.99,
    rating: 4.8,
    reviewCount: 50,
    imageIds: ['women-skirt-1'],
    sizes: ['S', 'M', 'L'],
    colors: ['Silver', 'Gold'],
    description: 'A knife-pleated skirt made from a metallic fabric that catches the light with every move.',
    details: ['Metallic-Coated Polyester', 'Elasticated Waistband', 'A-Line Silhouette', 'Below-the-Knee Length'],
    isTrending: true,
  },
  {
    id: '8',
    name: 'Chrono-Trench Coat',
    slug: 'chrono-trench-coat',
    category: 'Women',
    price: 450.00,
    rating: 5.0,
    reviewCount: 30,
    imageIds: ['women-coat-1'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Khaki'],
    description: 'A timeless trench coat updated with futuristic details like magnetic closures and a detachable hood.',
    details: ['Water-Resistant Gabardine', 'Double-Breasted Front', 'Detachable Hood', 'Belted Waist and Cuffs'],
    isTrending: true,
  },
];
